config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'top/main'
  resources :cartitems, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
  #root 'top#main'
  root 'products#index'
  #root 'cartitems#new'
  #root 'carts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cartitem
    has_many :product
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :cartitem, dependent: :destroy
    has_many :cart, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
        helper_method :current_cart
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
    def new
        @cartitem = Cartitem.new(product_id: params[:product_id])
    end
    def create
        @cartitem = Cartitem.new(qty: params[:cartitem][:qty], product_id: params[:cartitem][:product_id], cart_id: current_cart.id)
        @cartitem.save
        redirect_to root_path
    end
    def destroy
        cartitem = Cartitem.find(params[:id])
        cartitem.destroy
        redirect_to root_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @carts = Cartitem.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    def new
        @product = Product.new
    end
    def create
        @product = Product.new(name: params[:product][:name], price: params[:product][:price])
        @product.save
        redirect_to root_path
    end
    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<h2> カート登録ページ </h2>
<%= form_for @cartitem , url: {action: :create} do |f| %>
    商品名：<%= Product.find(@cartitem.product_id).name %><br>
    価格　：<%= Product.find(@cartitem.product_id).price %><br>
    <%= f.label :qty, '数量' %>
    <%= f.number_field :qty %><br>
    <%= f.hidden_field :product_id %>
    <%= f.submit 'カートに入れる' %>
<% end %>

app/views/carts/show.html.erb
<h2> カート </h2>
<% @carts.each do |cartitem| %>
    <p>
        商品名：<br>
        価格　：<br>
        数量　：<%= cartitem.qty %><br>
        <%= link_to '削除', "/cartitems/#{cartitem.id}", method: :delete %>
    </p><hr>
<% end %>
<%= link_to '戻る', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L62</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2> 商品一覧 </h2>
<% @products.each do |product| %>
    商品名：<%= product.name %><br>
    価格　：<%= product.price %> 円<br>
    <%= link_to '削除', "/products/#{product.id}", method: :delete %><br>
    <%= link_to 'カートに追加', new_cartitem_path(product_id: product.id) %><hr>
<% end %>
<%= link_to '商品登録', new_product_path %>

app/views/products/new.html.erb
<%= form_for @product , url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
    <%= f.submit '登録' %>
<% end %>